services:
  - type: web
    name: telegram2rss
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm run start
    autoDeploy: true

functions:
  - name: rss
    srcDir: functions/rss
    runtime: nodejs18
    path: /rss/:channel
